import { FeatureItem } from '../types';

export const FEATURES_DATA: FeatureItem[] = [
  {
    id: 'dars-e-nizami',
    title: 'Dars-e-Nizami Curriculum',
    titleUrdu: 'مکمل درسِ نظامی نصاب (8 سالہ)',
    titlePashto: 'د درسِ نظامي بشپړ نصاب (۸ کلن)',
    description: 'Systematic curriculum index mapping from A\'la (Class 1) to Dora-e-Hadith for madrasa students directly inside the app.',
    descriptionUrdu: 'درجہ اولیٰ تا دورۂ حدیث تمام درجات کی کتب، شروحات اور درسی نقشہ جات طلبہ و اساتذہ کے لیے دستیاب ہیں۔',
    descriptionPashto: 'له لومړۍ درجې (اولیٰ) څخه تر دورۂ حدیث پورې د ټولو کلونو درسي کتابونه، شروحات او منظم جدولونه.',
    iconName: 'GraduationCap',
    category: 'academic',
    highlights: ['Organized by 8 academic years', 'Sarf, Nahw, Fiqh & Usul index', 'Year-by-year syllabus tracking'],
    highlightsUrdu: ['8 تعلیمی درجات کے مطابق منظم ترتیب', 'صرف، نحو، فقہ اور اصول کا جامع اشاریہ', 'سال بہ سال نصاب کی مکمل فہرست'],
    highlightsPashto: ['د ۸ تعلیمي کلونو له مخې منظم جوړښت', 'د صرف، نحوې، فقهې او اصولو بشپړ نوملړ', 'کال په کال د کتابونو او درسونو ترتیب']
  },
  {
    id: 'quran-resources',
    title: 'Quranic Resources & Word-by-Word',
    titleUrdu: 'قرآن مجید اور لفظی و با محاورہ تراجم',
    titlePashto: 'قرآن کریم او کلمه په کلمه ژباړه',
    description: 'Complete Quranic text with word-by-word grammar breakdowns, translations, and verse analysis in the Android app.',
    descriptionUrdu: 'مکمل قرآن پاک، لفظی اور با محاورہ اردو و پشتو ترجمہ، اعراب، تلاش اور قراءت کی خصوصیات۔',
    descriptionPashto: 'بشپړ قرآن کریم له کلمه په کلمه ژباړې، معتبرو پښتو او اردو تفاسیرو او اسانه لټون سره.',
    iconName: 'Book',
    category: 'core',
    highlights: ['Word-by-word morphological analysis', 'Multiple classical translations', 'Verse bookmarking & study notes'],
    highlightsUrdu: ['کلمہ بہ کلمہ صرفی و نحوی تجزیہ', 'مستند تفاسیر اور معتبر تراجم', 'آیات کی نشاندہی اور ذاتی نوٹس'],
    highlightsPashto: ['کلمه په کلمه نحوي او صرفي شننه', 'معتبر پښتو او اردو تفاسیر', 'د مبارکو آیاتونو نښه کول او یادښتونه']
  },
  {
    id: 'chapter-quizzes',
    title: 'Chapter-wise Quizzes & MCQs',
    titleUrdu: 'سبق وار دینی کوئز اور امتحانات',
    titlePashto: 'د درسونو په کچه دیني کوئز او پوښتنې',
    description: 'Interactive multiple-choice assessment sets after each subject chapter to test knowledge inside the app.',
    descriptionUrdu: 'ہر سبق اور درسی موضوع کے بعد کثیر الانتخابی سوالات (MCQs) اور فوری تفصیلی وضاحتی نتائج۔',
    descriptionPashto: 'د هر درسي کتاب او موضوع نه وروسته څو انتخابي پوښتنې (MCQs) او سمدستي تفصیلي ځوابونه.',
    iconName: 'HelpCircle',
    category: 'study',
    highlights: ['Topic-focused MCQ pools', 'Immediate option verification', 'Detailed answer explanations'],
    highlightsUrdu: ['موضوع وار 1500+ سوالات کا ذخیرہ', 'فوری صحیح اور غلط کی نشاندہی', 'مستند کتب سے تفصیلی حوالہ جات'],
    highlightsPashto: ['له ۱۵۰۰ څخه زیاتې درسي او دیني پوښتنې', 'سمدستي د سم او غلط ځواب ښودل', 'له مستندو درسي کتابونو تفصیلي وضاحت']
  },
  {
    id: 'ai-assistant',
    title: 'AI Learning Assistant & Scholar',
    titleUrdu: 'اسلامی AI علمی معاون',
    titlePashto: 'د اسلامي علومو AI علمي مرستیال',
    description: 'An on-device AI tutor in the Android app answering questions on Sarf conjugations, Nahw rules, and Fiqh terminology.',
    descriptionUrdu: 'صرفی گردانوں، نحوی تراکیب، فقہی اصطلاحات اور احادیث کے راویوں کے بارے میں فوری رہنمائی۔',
    descriptionPashto: 'د صرفي ګردانونو، نحوي ترکیبونو، فقهي اصطلاحاتو او علمي پوښتنو په اړه سمدستي ځوابونه.',
    iconName: 'Bot',
    category: 'ai',
    highlights: ['Grammar & syntax breakdown', 'Verified book citations', 'Multilingual Arabic, Urdu & English'],
    highlightsUrdu: ['نحوی و صرفی قواعد کی آسان توضیح', 'معتبر درسی کتب کے حوالے', 'عربی، اردو، پشتو اور انگلش میں رہنمائی'],
    highlightsPashto: ['د صرف او نحوې د اصولو اسانه تشریح', 'د معتبرو دیني کتابونو حوالې', 'په پښتو، اردو او عربي ژبو مرسته']
  },
  {
    id: 'progress-tracking',
    title: 'Progress & Streak Tracking',
    titleUrdu: 'تعلیمی پیش رفت اور مطالعہ کا ریکارڈ',
    titlePashto: 'د مطالعې پرمختګ او ورځنی ریکارډ',
    description: 'Monitor overall syllabus completion, subject mastery, streak days, and quiz analytics on your Android device.',
    descriptionUrdu: 'مکمل نصاب کی تکمیل کا فیصد، روزانہ مطالعہ کی ترتیب، اور کوئز اسکورز کا گرافیکل چارٹ۔',
    descriptionPashto: 'د بشپړ شوي نصاب سلنه، د مطالعې ورځنی تسلسل او د امتحاني نمرو تفصیلي چارټونه.',
    iconName: 'BarChart3',
    category: 'study',
    highlights: ['Visual progress bars & score analytics', 'Daily learning streak tracker', 'Subject-wise mastery stats'],
    highlightsUrdu: ['پیش رفت کے تصویری چارٹس اور اسکور', 'روزانہ مطالعہ کا اسٹریک ٹریکر', 'مضمون وار مہارت کے اعداد و شمار'],
    highlightsPashto: ['د پرمختګ ګرافونه او تحلیلي چارټونه', 'د ورځنۍ زده کړې پرله پسې حساب', 'د کتابونو په کچه د پوهې کچه']
  },
  {
    id: 'reference-index',
    title: 'Book & Reference Index',
    titleUrdu: 'کتب و شروحات کا جامع اشاریہ',
    titlePashto: 'د کتابونو او شروحاتو جامع نوملړ',
    description: 'Structured index enabling madrasa students to organize, cross-reference, and locate classical primers.',
    descriptionUrdu: 'درسِ نظامی کی بنیادی متون اور شروحات کو آسانی سے تلاش کرنے اور مطالعہ کرنے کا منظم انڈیکس۔',
    descriptionPashto: 'د درسِ نظامي د اصلي کتابونو او شروحاتو د اسانه لټون او مطالعې منظم انډیکس.',
    iconName: 'BookOpen',
    category: 'academic',
    highlights: ['Subject & author categorization', 'Searchable reference metadata', 'Cross-referenced study notes'],
    highlightsUrdu: ['مصنفین اور مضامین کے لحاظ سے درجہ بندی', 'تیز رفتار اور درست سرچ سسٹم', 'مربوط درسی مطالعہ نوٹس'],
    highlightsPashto: ['د لیکوالانو او موضوعاتو پر بنسټ وېش', 'د پلټنې او لټون چټک سیسټم', 'تړلي درسي یادښتونه او لارښوونې']
  },
  {
    id: 'bookmarks',
    title: 'Smart Bookmarks & Notes',
    titleUrdu: 'اسمارٹ بک مارکس اور ذاتی نوٹس',
    titlePashto: 'ځیرک بک مارکونه او شخصي یادښتونه',
    description: 'Save key definitions, complex grammar rules, difficult quiz questions, and important pages instantly.',
    descriptionUrdu: 'اہم تعریفات، نحوی قواعد، مشکل سوالات اور صفحات کو ایک کلک پر محفوظ کریں۔',
    descriptionPashto: 'مهم تعریفونه، ګرامري قواعد، سختې پوښتنې او پاڼې په اسانۍ سره خوندي کړئ.',
    iconName: 'Bookmark',
    category: 'core',
    highlights: ['One-tap bookmarking', 'Custom tagged collections', 'Quick jump-to-source navigation'],
    highlightsUrdu: ['ایک ٹچ پر بک مارکنگ', 'مخصوص ٹیگز اور فولڈرز', 'براہ راست صفحہ پر پہنچنے کی سہولت'],
    highlightsPashto: ['په یوه تڼۍ نښه کول', 'ځانګړي فولډرونه او نوملړونه', 'اصلي متن ته د ژر ورتګ اسانتیا']
  },
  {
    id: 'dark-light-mode',
    title: 'Islamic Dark & Light Themes',
    titleUrdu: 'اسلامی ڈارک اور لائٹ موڈ',
    titlePashto: 'اسلامي تیاره (ډارک) او روښانه بڼه',
    description: 'Eye-friendly app themes tailored for comfortable late-night revision and crisp daytime reading.',
    descriptionUrdu: 'آنکھوں کی حفاظت کے لیے تیار کردہ شاہی زمردی ڈارک موڈ اور دن کے مطالعہ کے لیے لائٹ تھیم۔',
    descriptionPashto: 'د سترګو د هوساینې لپاره شاهي زمردي ډارک موډ او د ورځې د مطالعې روښانه بڼه.',
    iconName: 'Moon',
    category: 'core',
    highlights: ['Amoled dark emerald theme', 'High contrast light reader', 'Automatic system theme matching'],
    highlightsUrdu: ['شاہی زمردی (Emerald) نائٹ موڈ', 'ہائی کنٹراسٹ ڈے ریڈر تھیم', 'سسٹم تھیم سے خودکار مطابقت'],
    highlightsPashto: ['ښکلی زمردي تور موډ د شپې مطالعې لپاره', 'روښانه بڼه د ورځې د لوستلو لپاره', 'د موبایل سیسټم سره پخپله سمون']
  }
];
